### ISSUE TITLE
the meaning of additional information in predict_result

### ISSUE THREAD

**Issue by whateverxzy** [bm2-lab/scLearn#10]
I ran the codes that you provided in github, and I got the scLearn_predict_result. But I have a problem about the the meaning of additional information in predict_result. I have read the codes that how to get additional information, still have no clues. What'more, I can't find the types of query cells, so I don't know how to get the accuracy of scLearn. You don't provide  the types of query cells and the method of how to get the accuracy. I really hope to receive your reply. I will appreciate it if you can solve my problems.

**Comment by BinDuan** [comment]
> I ran the codes that you provided in github, and I got the scLearn_predict_result. But I have a problem about the the meaning of additional information in predict_result. I have read the codes that how to get additional information, still have no clues. What'more, I can't find the types of query cells, so I don't know how to get the accuracy of scLearn. You don't provide the types of query cells and the method of how to get the accuracy. I really hope to receive your reply. I will appreciate it if you can solve my problems.

Sorry not to say it clearly. The additional information is the detailed information of predicted results. For example, if scLearn predicted a query cell "A" cell type, then the additional information means the detailed correlation. If scLearn predicted a query cell "unassigned", the additional information means what kinds of "unassigned", because we think there are two kinds of "unassigned" result, one is because this query cell is too similar to multiple cell types, the other one is because this query cell is belong to novel cell type. 

As for the true cell type of query cells, we indeed didn't offer this information in our tutorial, because the purpose of this purpose is to show how to use scLearn to predict cell type. Therefore, if you want to evaluate the performance of scLearn, it would be better to use your own golden datasets.

Hope this helps.

**Comment by BinDuan** [comment]
> I ran the codes that you provided in github, and I got the scLearn_predict_result. But I have a problem about the the meaning of additional information in predict_result. I have read the codes that how to get additional information, still have no clues. What'more, I can't find the types of query cells, so I don't know how to get the accuracy of scLearn. You don't provide the types of query cells and the method of how to get the accuracy. I really hope to receive your reply. I will appreciate it if you can solve my problems.

In fact, we offered the true cell type label of test datasets with annotation "### the true labels of this test datasets ". You need this information.

**Comment by BinDuan** [comment]
> I ran the codes that you provided in github, and I got the scLearn_predict_result. But I have a problem about the the meaning of additional information in predict_result. I have read the codes that how to get additional information, still have no clues. What'more, I can't find the types of query cells, so I don't know how to get the accuracy of scLearn. You don't provide the types of query cells and the method of how to get the accuracy. I really hope to receive your reply. I will appreciate it if you can solve my problems.

In fact, we offered the true cell type label of test datasets with annotation "### the true labels of this test datasets ". You can use this information by run next codes in our tutorial:

query_ann<-as.character(data2$cell_type1)
names(query_ann)<-colnames(data2)

Hope it helps!

**Comment by whateverxzy** [comment]
Thank you for your reply. Your answer is very helpful and clear, but I am a little confused about the explanation of additional information. Does it mean the probability of the query cell type is predicted  as 'A' type?

**Comment by BinDuan** [comment]
> Thank you for your reply. Your answer is very helpful and clear, but I am a little confused about the explanation of additional information. Does it mean the probability of the query cell type is predicted as 'A' type?

Yes, you are right
